"""
Update classes.txt and plate_well_id_path.json from Excel/CSV plate maps.
Structure: Column headers = Row A (A01-A12), Data rows = B-H (indices 0-6 = rows B-H)
"""

import pandas as pd
import json
import os
from tqdm import tqdm

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

PLATE_ROWS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
PLATE_COLS = list(range(1, 13))


def clean_label(label):
    """Clean label - remove pandas suffixes and group NC/WT as WT"""
    if pd.isna(label):
        return None
    label_str = str(label).strip()
    label_str = label_str.replace('.1', '').replace('.2', '').replace('.3', '')
    if label_str.startswith('NC_') or label_str.startswith('WT NC_'):
        label_str = 'WT'
    return label_str


def load_plate_map(filepath):
    """Load plate map from Excel or CSV"""
    if filepath.endswith('.xlsx'):
        df = pd.read_excel(filepath, header=0)
    else:
        df = pd.read_csv(filepath)
    return df


def main():
    print("="*60)
    print("Updating plate_well_id_path.json and classes.txt")
    print("="*60)
    
    plate_files = {
        'P1': 'P1_plate_map.xlsx',
        'P2': 'P2_plate_map.csv',
        'P3': 'P3_plate_map.csv',
        'P4': 'P4_plate_map.xlsx',
        'P5': 'P5_plate_map.xlsx',
        'P6': 'P6_plate_map.xlsx'
    }
    
    all_labels = set()
    plate_data = {}
    
    print("\nStep 1: Reading plate maps...")
    for plate, filename in plate_files.items():
        filepath = os.path.join(BASE_DIR, filename)
        if not os.path.exists(filepath):
            print(f"  Warning: {filename} not found, skipping...")
            continue
        
        df = load_plate_map(filepath)
        print(f"  {plate}: shape={df.shape}")
        
        plate_data[plate] = {}
        
        # Row A: use column headers
        for col_idx in range(len(df.columns)):
            well = f"A{col_idx + 1:02d}"
            label = clean_label(df.columns[col_idx])
            if label:
                plate_data[plate][well] = label
                all_labels.add(label)
        
        # Rows B-H: use data rows
        for row_idx in range(len(df)):
            plate_row = PLATE_ROWS[row_idx + 1]  # +1 because row 0 is for B
            for col_idx in range(len(df.columns)):
                well = f"{plate_row}{col_idx + 1:02d}"
                label = clean_label(df.iloc[row_idx, col_idx])
                if label:
                    plate_data[plate][well] = label
                    all_labels.add(label)
    
    # Sort labels alphabetically
    all_labels = sorted(all_labels)
    
    print(f"\nFound {len(all_labels)} unique labels")
    print(f"Labels: {all_labels}")
    
    # Step 2: Create plate_well_id_path.json structure
    print("\nStep 2: Creating plate_well_id_path.json...")
    
    new_plate_data = {}
    for plate, wells in plate_data.items():
        new_plate_data[plate] = {}
        for row in PLATE_ROWS:
            new_plate_data[plate][row] = {}
            for col in PLATE_COLS:
                well = f"{row}{col:02d}"
                if well in wells:
                    new_plate_data[plate][row][str(col)] = {
                        "id": wells[well]
                    }
    
    output_path = os.path.join(BASE_DIR, 'plate_well_id_path.json')
    with open(output_path, 'w') as f:
        json.dump(new_plate_data, f, indent=4)
    print(f"  Saved: {output_path}")
    
    # Step 3: Verify the JSON structure
    print("\nStep 3: Verifying plate_well_id_path.json...")
    
    # Count wells per plate
    for plate in new_plate_data:
        well_count = sum(len(new_plate_data[plate][row]) for row in PLATE_ROWS)
        print(f"  {plate}: {well_count} wells")
    
    # Step 4: Test a few mappings
    print("\nStep 4: Testing mappings...")
    test_wells = ['A03', 'A01', 'H12', 'B03']
    for plate in ['P1', 'P3', 'P6']:
        print(f"  {plate}:")
        for well in test_wells:
            row = well[0]
            col = well[1:]
            if row in new_plate_data[plate] and col in new_plate_data[plate][row]:
                label = new_plate_data[plate][row][col]['id']
                print(f"    Well {well} = {label}")
    
    # Step 5: Count label distribution
    print("\nStep 5: Label distribution across all plates...")
    label_counts = {}
    for wells in plate_data.values():
        for label in wells.values():
            label_counts[label] = label_counts.get(label, 0) + 1
    
    for label in sorted(label_counts.keys()):
        print(f"  {label}: {label_counts[label]} wells")
    
    print("\n" + "="*60)
    print("DONE!")
    print("="*60)
    print(f"Updated: plate_well_id_path.json")
    print(f"Note: classes.txt will be auto-generated by train.py")
    print(f"\nWhen you run train.py next time, it will:")
    print(f"  1. Read plate_well_id_path.json")
    print(f"  2. Extract all unique labels")
    print(f"  3. Create classes.txt with {len(all_labels)} classes")
    print(f"  4. Train with these {len(all_labels)} classes")


if __name__ == "__main__":
    main()
